var pokemon = "Gengar";
var gengarHp = 60;
var gengarNum = 93;
var gengarBestMove = " Dream Eater";
var Dream_Eater_AD = 100;
var gengarWorstMove = "Lick";
var Lick_AD = 30;
var gengarLastEvo = true 
var gengarEvos = 3 
